<?php

namespace Database\Seeders;

use App\Models\location\Metro;
use Illuminate\Database\Seeder;

class MetroSeeder extends Seeder
{
    public function run()
    {
        Metro::create(['title' => 'Авиамоторная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Автозаводская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Академическая', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Александровский сад', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Алексеевская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Алма-Атинская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Алтуфьево', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Аминьевская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Андроновка', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Аникеевка', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Аннино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Апрелевка', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Арбатская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Аэропорт', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Аэропорт Внуково', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Бабушкинская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Багратионовская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Баковка', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Балтийская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Баррикадная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Бауманская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Беговая', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Белокаменная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Беломорская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Белорусская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Беляево', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Бескудниково', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Бибирево', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Библиотека имени Ленина', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Битца', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Битцевский парк', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Борисово', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Борисово', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Боровицкая', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Боровское шоссе', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Ботанический сад', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Братиславская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Бульвар Дмитрия Донского', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Бульвар Рокоссовского', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Бульвар адмирала Ушакова', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Бунинская аллея', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Бутово', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Бутырская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Быково', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'ВДНХ', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Варшавская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Верхние Котлы', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Верхние Лихоборы', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Вешняки', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Владыкино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Внуково', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Водники', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Водный стадион', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Войковская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Волгоградский проспект', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Волжская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Волоколамская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Волхонка', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Воробьевы горы', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Воронцовская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Выставочная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Выставочный центр', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Выхино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Говорово', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Гражданская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Грачёвская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Давыдково', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Дегунино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Деловой центр', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Депо', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Динамо', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Дмитровская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Добрынинская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Долгопрудная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Домодедовская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Дорогомиловская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Достоевская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Дубровка', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Есенинская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Жулебино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'ЗИЛ', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Зеленоград - Крюково', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Зорге', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Зюзино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Зябликово', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Измайлово', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Измайловская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Ильинская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Ипподром', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Калитники', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Калужская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Кантемировская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Каховская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Каширская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Киевская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Китай-город', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Кленовый бульвар', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Кожуховская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Кокошкино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Коломенская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Коммунарка', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Комсомольская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Коньково', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Коптево', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Косино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Котельники', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Красково', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Красногвардейская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Красногорская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Краснопресненская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Красносельская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Красные ворота', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Красный Балтиец', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Красный Строитель', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Кратово', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Крестьянская застава', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Кропоткинская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Крылатское', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Крымская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Крёкшино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Кузнецкий мост', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Кузьминки', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Кунцевская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Курская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Курьяново', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Кусково', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Кутузовская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Кучино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Левобережная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Ленинский проспект', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Лермонтовский проспект', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Лесной городок', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Лесопарковая', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Лефортово', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Лианозово', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Лихоборы', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Лобня', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Локомотив', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Ломоносовский проспект', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Лубянка', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Лужники', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Лухмановская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Люберцы', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Люблино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Малаховка', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Малино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Марк', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Марксистская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Марьина роща', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Марьино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Матвеевская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Маяковская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Медведково', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Международная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Менделеевская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Мещерская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Минская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Митино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Митьково', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Мичуринец', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Мичуринский проспект', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Мнёвники', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Молжаниново', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Молодежная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Москва-Товарная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Москворечье', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Моссельмаш', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Мякинино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Нагатинская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Нагатинский Затон', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Нагорная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Народное Ополчение', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Нахабино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Нахимовский проспект', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Некрасовка', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Немчиновка', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Нижегородская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Никольское', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Новаторская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Новогиреево', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Новодачная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Новокосино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Новокузнецкая', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Новопеределкино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Новоподрезково', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Новослободская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Новохохловская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Новоясеневская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Новые Черемушки', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Одинцово', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Озёрная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Окружная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Окская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Октябрьская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Октябрьское поле', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Ольгино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Ольховая', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Опалиха', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Орехово', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Останкино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Остафьево', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Отдых', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Отрадное', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Охотный ряд', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Очаково', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Павелецкая', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Павшино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Панки', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Панфиловская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Парк Победы', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Парк культуры', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Партизанская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Пенягино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Первомайская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Переделкино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Перерва', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Перово', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Петровский парк', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Петровско-Разумовская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Печатники', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Пионерская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Планерная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Площадь Гагарина', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Площадь Ильича', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Площадь Революции', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Площадь трёх вокзалов', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Плющево', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Плющиха', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Победа', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Подольск', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Подрезково', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Поклонная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Покровское', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Полежаевская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Полянка', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Пражская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Преображенская площадь', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Прокшино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Пролетарская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Проспект Вернадского', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Проспект Мира', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Профсоюзная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Пушкинская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Пыхтино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Пятницкое шоссе', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Рабочий поселок', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Раменки', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Раменское', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Рассказовка', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Реутов', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Речной вокзал', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Рижская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Римская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Ростокино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Румянцево', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Рязанский проспект', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Савеловская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Саларьево', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Салтыковская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Санино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Свиблово', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Севастопольская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Селигерская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Семеновская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Серп и Молот', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Серпуховская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Сетунь', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Силикатная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Сколково', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Славянский бульвар', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Смоленская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Сокол', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Соколиная Гора', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Сокольники', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Солнечная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Солнцево', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Сортировочная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Спартак', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Спортивная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Сретенский бульвар', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Стахановская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Стрешнево', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Строгино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Студенческая', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Суворовская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Сухаревская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Сходненская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Сходня', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Таганская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Тверская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Театральная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Текстильщики', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Телецентр', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Теплый Стан', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Терехово', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Тестовская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Технопарк', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Тимирязевская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Толстопальцево', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Томилино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Третьяковская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Трикотажная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Тропарёво', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Трубная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Тульская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Тургеневская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Тушинская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Угрешская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Удельная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Улица 1905 года', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Улица Академика Королёва', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Улица Горчакова', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Улица Милашенкова', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Улица Сергея Эйзенштейна', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Улица Скобелевская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Улица Старокачаловская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Улица академика Янгеля', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Университет', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Ухтомская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Фабричная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Физтех', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Филатов луг', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Филевский парк', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Фили', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Фирсановская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Фонвизинская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Фрунзенская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Химки', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Хлебниково', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Ховрино', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Хорошевская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Хорошёво', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'ЦСКА', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Царицыно', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Цветной бульвар', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Черкизовская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Чертановская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Чеховская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Чистые пруды', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Чкаловская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Чухлинка', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Шаболовская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Шелепиха', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Шереметьевская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Шипиловская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Шоссе Энтузиастов', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Щелковская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Щербинка', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Щукинская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Электрозаводская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Юго-Восточная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Юго-Западная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Южная', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Ясенево', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Яхромская', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'улица Дмитриевского', 'city_id' => 19, 'status' => 1]);
        Metro::create(['title' => 'Автово', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Адмиралтейская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Академическая', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Балтийская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Бухарестская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Василеостровская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Владимирская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Волковская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Выборгская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Горьковская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Гостиный двор', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Гражданский проспект', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Девяткино', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Достоевская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Елизаровская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Звездная', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Звенигородская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Кировский завод', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Комендантский проспект', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Крестовский остров', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Купчино', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Ладожская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Ленинский проспект', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Лесная', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Лиговский проспект', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Ломоносовская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Маяковская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Международная', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Московская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Московские ворота', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Нарвская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Невский проспект', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Новочеркасская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Обводный канал', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Обухово', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Озерки', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Парк Победы', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Парнас', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Петроградская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Пионерская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Площадь Александра Невского', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Площадь Восстания', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Площадь Ленина', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Площадь Мужества', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Политехническая', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Приморская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Пролетарская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Проспект Большевиков', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Проспект Ветеранов', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Проспект Просвещения', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Пушкинская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Рыбацкое', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Садовая', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Сенная площадь', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Спасская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Спортивная', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Старая Деревня', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Технологический институт', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Удельная', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Улица Дыбенко', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Фрунзенская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Черная речка', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Чернышевская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Чкаловская', 'city_id' => 30, 'status' => 1]);
        Metro::create(['title' => 'Электросила', 'city_id' => 30, 'status' => 1]);
    }
}
