<?php

namespace Database\Seeders;

use App\Models\location\Zone;
use Illuminate\Database\Seeder;

class ZoneSeeder extends Seeder
{
    public function run()
    {
        Zone::create(['title' => 'Арбат', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Басманный', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Замоскворечье', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Красносельский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Мещанский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Пресненский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Таганский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Тверской', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Хамовники', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Якиманка', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Аэропорт', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Беговой', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Бескудниковский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Войковский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Восточное Дегунино', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Головинский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Дмитровский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Западное Дегунино', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Коптево', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Левобережный', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Молжаниновский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Савёловский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Сокол', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Тимирязевский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Ховрино', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Хорошёвский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Алексеевский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Алтуфьевский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Бабушкинский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Бибирево', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Бутырский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Лианозово', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Лосиноостровский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Марфино', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Марьина Роща', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Останкинский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Отрадное', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Ростокино', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Свиблово', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Северное Медведково', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Северный', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Южное Медведково', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Ярославский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Выхино-Жулебино', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Капотня', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Кузьминки', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Лефортово', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Люблино', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Марьино', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Некрасовка', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Нижегородский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Печатники', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Рязанский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Текстильщики', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Южнопортовый', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Бирюлёво Восточное', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Бирюлёво Западное', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Братеево', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Даниловский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Донской', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Зябликово', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Москворечье-Сабурово', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Нагатино-Садовники', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Нагатинский Затон', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Нагорный', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Орехово-Борисово Северное', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Орехово-Борисово Южное', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Царицыно', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Чертаново Северное', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Чертаново Центральное', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Чертаново Южное', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Богородское', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Вешняки', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Восточное Измайлово', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Восточный', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Гольяново', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Ивановское', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Измайлово', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Косино-Ухтомский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Метрогородок', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Новогиреево', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Новокосино', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Перово', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Преображенское', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Северное Измайлово', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Соколиная гора', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Сокольники', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Внуково', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Дорогомилово', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Крылатское', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Кунцево', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Можайский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Ново-Переделкино', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Очаково-Матвеевское', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Проспект Вернадского', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Раменки', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Солнцево', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Тропарёво-Никулино', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Филёвский Парк', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Фили-Давыдково', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Академический', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Гагаринский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Зюзино', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Коньково', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Котловка', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Ломоносовский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Обручевский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Северное Бутово', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Тёплый Стан', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Черёмушки', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Южное Бутово', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Ясенево', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Куркино', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Митино', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Покровское-Стрешнево', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Северное Тушино', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Строгино', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Хорошёво-Мнёвники', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Щукино', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Южное Тушино', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Зеленоград', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Крюково', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Матушкино', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Савёлки', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Силино', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Старое Крюково', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Московский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Сосенское', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Внуковское', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Воскресенское', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Вороновское', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Десёновское', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Киевский', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Клёновское', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Кокошкино', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Краснопахорское', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Марушкинское', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Михайлово-Ярцевское', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Мосрентген', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Новофёдоровское', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Первомайское', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Роговское', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Рязановское', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Троицк', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Филимонковское', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Щаповское', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Щербинка', 'city_id' => 19, 'status' => 1]);
        Zone::create(['title' => 'Адмиралтейский', 'city_id' => 2, 'status' => 1]);
        Zone::create(['title' => 'Василеостровский', 'city_id' => 2, 'status' => 1]);
        Zone::create(['title' => 'Выборгский', 'city_id' => 2, 'status' => 1]);
        Zone::create(['title' => 'Калининский', 'city_id' => 2, 'status' => 1]);
        Zone::create(['title' => 'Кировский', 'city_id' => 2, 'status' => 1]);
        Zone::create(['title' => 'Колпинский', 'city_id' => 2, 'status' => 1]);
        Zone::create(['title' => 'Красногвардейский', 'city_id' => 2, 'status' => 1]);
        Zone::create(['title' => 'Красносельский', 'city_id' => 2, 'status' => 1]);
        Zone::create(['title' => 'Кронштадтский', 'city_id' => 2, 'status' => 1]);
        Zone::create(['title' => 'Курортный', 'city_id' => 2, 'status' => 1]);
        Zone::create(['title' => 'Московский', 'city_id' => 2, 'status' => 1]);
        Zone::create(['title' => 'Невский', 'city_id' => 2, 'status' => 1]);
        Zone::create(['title' => 'Петроградский', 'city_id' => 2, 'status' => 1]);
        Zone::create(['title' => 'Петродворцовый', 'city_id' => 2, 'status' => 1]);
        Zone::create(['title' => 'Приморский', 'city_id' => 2, 'status' => 1]);
        Zone::create(['title' => 'Пушкинский', 'city_id' => 2, 'status' => 1]);
        Zone::create(['title' => 'Фрунзенский', 'city_id' => 2, 'status' => 1]);
        Zone::create(['title' => 'Центральный', 'city_id' => 2, 'status' => 1]);
    }
}
